### PR TITLE
Copy UTTT model into UTTT game server repository

### PR DESCRIPTION
**Pull request by reddyalready**
This copies, preserving history, the UTTT model src and test folders, so we can combine them into one repo and prevent further confusion about what these repos are.

### CODE REVIEW

**Comment by joffat** [comment]
Why do we want to pull this in? It is used by the JS players also. We would need them to pull it in along with the game servers from npm. Or is the plan to publish only part of it?

**Comment by reddyalready** [comment]
So my plan was to use Lerna to publish multiple packages from this repo, the api/model dependency and the server which would depend on that. This might be a complicated way to approach though and perhaps it's better to (as you say) rename the model repo and package to `uttt-model` and call it a day. Thoughts?

**Comment by reddyalready** [comment]
If going with the multi-repo way, `ultimate-ttt-engine` might be a better name since it's not just a data model.

**Comment by joffat** [comment]
> 
> 
> So my plan was to use Lerna to publish multiple packages from this repo, the api/model dependency and the server which would depend on that. This might be a complicated way to approach though and perhaps it's better to (as you say) rename the model repo and package to `uttt-model` and call it a day. Thoughts?

I am all for this. Lets do it.

**Comment by aurbano** [comment]
Sounds good to me as well! Just slightly more complicated at first but ensuring the same version is used on both will be helpful 👍🏼

**Comment by reddyalready** [comment]
Taking this forward in #53.

**Pull request closed without merging**
